name: ci

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Prepare
        run: npm run dev:prepare

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm run test
